version: "3.9"

services:
  backend:
    build: ./backend
    container_name: graphql-backend
    ports:
      - "4000:4000"

  nginx:
    build: ./nginx
    container_name: graphql-nginx
    ports:
      - "80:80"
    depends_on:
      - backend

